name: Docker and Terraform Deployment

on:
  push:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up rclone config
      run: |
        echo "[oci]" >> rclone.conf
        echo "type = s3" >> rclone.conf
        echo "provider = Other" >> rclone.conf
        echo "access_key_id = ${{ secrets.OCI_ACCESS_KEY }}" >> rclone.conf
        echo "secret_access_key = ${{ secrets.OCI_SECRET_KEY }}" >> rclone.conf
        echo "endpoint = ${{ secrets.OCI_ENDPOINT }}" >> rclone.conf
        echo "location_constraint = ${{ secrets.OCI_REGION }}" >> rclone.conf
        echo "" >> rclone.conf  # Add a blank line between configurations

        echo "[s3]" >> rclone.conf
        echo "type = s3" >> rclone.conf
        echo "provider = AWS" >> rclone.conf
        echo "env_auth = false" >> rclone.conf
        echo "access_key_id = ${{ secrets.AWS_ACCESS_KEY }}" >> rclone.conf
        echo "secret_access_key = ${{ secrets.AWS_SECRET_KEY }}" >> rclone.conf
        echo "region = ${{ secrets.AWS_REGION }}" >> rclone.conf
        echo "acl = private" >> rclone.conf
      
    - name: Log in to Oracle Cloud Infrastructure Registry
      run: echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login -u "id64xepqbqwr/alexmh25@hotmail.com" --password-stdin iad.ocir.io
        
    - name: Build Docker image
      run: docker build -t iad.ocir.io/id64xepqbqwr/alex/terr-test:latest .
        
    - name: Push Docker image
      run: docker push iad.ocir.io/id64xepqbqwr/alex/terr-test:latest

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Build and push Docker image
    #   run: |
    #     docker login -u "id64xepqbqwr/alexmh25@hotmail.com" -p "$OCI_AUTH_TOKEN" iad.ocir.io && \
    #     docker buildx create --use && \
    #     docker buildx build --platform linux/amd64 -t iad.ocir.io/id64xepqbqwr/alex/terr-test --push .
    #   env:
    #     OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}